apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ama-metrics-pdb
  namespace: {{ $.Values.namespace }}
  labels:
    component: ama-metrics-pdb
    kubernetes.azure.com/managedby: aks
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      rsName: ama-metrics
  unhealthyPodEvictionPolicy: AlwaysAllow
