kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ama-metrics-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: ama-metrics-serviceaccount
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: ClusterRole
  name: ama-metrics-reader
  apiGroup: rbac.authorization.k8s.io
