apiVersion: v1
kind: Service
metadata:
  name: ama-metrics-ksm
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: ama-metrics
    app.kubernetes.io/name: ama-metrics-ksm
    app.kubernetes.io/part-of: ama-metrics-ksm
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: azure-monitor-metrics-addon-0.1.0
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: "ClusterIP"
  ports:
  - name: "http"
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: ama-metrics-ksm
