apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-prometheus-reference-app
spec:
  selector:
    matchLabels:
      app: win-prometheus-reference-app
  replicas: 1
  template:
    metadata:
      labels:
        app: win-prometheus-reference-app
    spec:
      containers:
        - name: win-prometheus-reference-app-golang
          image: mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:6.7.5-main-09-12-2023-8fbde9ca-win-ref-app-golang
          resources:
            limits:
              cpu: 2
              memory: 2Gi
          env:
            - name: RUN_PERF_TEST
              value: "true"
            - name: SCRAPE_INTERVAL
              value: "15"
            - name: METRIC_COUNT
              value: "62500"
          ports:
            - containerPort: 2112
              protocol: TCP
            - containerPort: 2113
              protocol: TCP
        - name: win-prometheus-reference-app-python
          image: mcr.microsoft.com/azuremonitor/containerinsights/cidev/prometheus-collector/images:6.7.5-main-09-12-2023-8fbde9ca-win-ref-app-python
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
          - containerPort: 2114
            protocol: TCP
      nodeSelector:
        kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: win-prometheus-reference-service
spec:
  selector:
    app: win-prometheus-reference-app
  ports:
    - name: "weather-app"
      protocol: TCP
      port: 2112
      targetPort: 2112
    - name: "untyped-metrics"
      protocol: TCP
      port: 2113
      targetPort: 2113
    - name: "python-client"
      protocol: TCP
      port: 2114
      targetPort: 2114
  internalTrafficPolicy: Local
