AzureMonitorMetrics:
  KubeStateMetrics:
# Uncomment the below 2 settings if you want to pass in the labels and/or annotations
    #MetricLabelsAllowlist: "testlabel=[.*]"
    #MetricAnnotationsAllowList: ""
    ImageRepository: "/oss/kubernetes/kube-state-metrics"
# Kube-state-metrics ImageTag - v2.6.0, corresponds to chart version - 4.23.0
    ImageTag: "v2.6.0"
    Collectors:
      - certificatesigningrequests
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - endpoints
      - horizontalpodautoscalers
      - ingresses
      - jobs
      - leases
      - limitranges
      - mutatingwebhookconfigurations
      - namespaces
      - networkpolicies
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - poddisruptionbudgets
      - pods
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - secrets
      - services
      - statefulsets
      - storageclasses
      - validatingwebhookconfigurations
      - volumeattachments
  ImageRepository: "/azuremonitor/containerinsights/cidev/prometheus-collector/images"
  ImageTag: "6.1.0-grace-no-9090-01-12-2023-094e4e1a"
  # The below 2 settings are not Azure Monitor Metrics adapter chart. They are substituted in a different manner. 
  # Please update these with the latest ones from here so that you get the image that is currently deployed by the AKS RP - 
  # Repository: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/addon-charts/azure-monitor-metrics-addon/templates/ama-metrics-daemonset.yaml&version=GBrashmi/prom-addon-arm64&line=136&lineEnd=136&lineStartColumn=56&lineEndColumn=85&lineStyle=plain&_a=contents
  # ImageTag: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/kube-control-plane/templates/_images.tpl&version=GBrashmi/prom-addon-arm64&line=530&lineEnd=530&lineStartColumn=28&lineEndColumn=53&lineStyle=plain&_a=contents
  AddonTokenAdapter:
    ImageRepository: "/aks/msi/addon-token-adapter"
    ImageTag: "master.221118.2"
  ArcExtension: true
global:
  commonGlobals:
    CloudEnvironment: "Public"
    Region: "West US 3"
    Customer:
      # might need to figure out what the arc values path is to add to collector
      # if arc extension, use the arc version of this in daemonset and deployment
      AzureResourceID: "/subscriptions/b9842c7c-1a38-4385-8f39-a51314758bcf/resourcegroups/marc-test-arc-prom/providers/Microsoft.Kubernetes/connectedClusters/marc-test-arc-onprem3"
# Azure:
#   Cluster:
#     ResourceID: "/subscriptions/b9842c7c-1a38-4385-8f39-a51314758bcf/resourcegroups/marc-test-arc-prom/providers/Microsoft.Kubernetes/connectedClusters/marc-test-arc-onprem3"
#     Region: "westus3"

# Azure: 
#   Identity:
#       MSIAdapterYaml: |- 
#         - name: MANAGED_IDENTITY_AUTH
#           value: "true"
#         - name: TEST_MODE
#           value: "true"
#         - name: TEST_FILE
#           value: "/data/token"
#         image: "mcr.microsoft.com/aks/msi/addon-token-adapter:master.220916.1"
#         securityContext:
#           capabilities:
#             add:
#               - NET_ADMIN
#               - NET_RAW
#         livenessProbe:
#           httpGet:
#             path: /healthz
#             port: 9090
#             scheme: "HTTP"
#           initialDelaySeconds: 10
#           periodSeconds: 15
#         resources:
#           limits:
#             cpu: 50m
#             memory: 100Mi
#           requests:
#             cpu: 20m
#             memory: 50Mi