  scrape_configs:
  - job_name: kube-state-metrics
    label_limit: 63
    label_name_length_limit: 511
    label_value_length_limit: 1023
    static_configs:
    - targets: ['$$KUBE_STATE_NAME$$.$$POD_NAMESPACE$$.svc.cluster.local:8080']
