  scrape_configs:
  - job_name: kubelet-windows
    scheme: https
    metrics_path: /metrics
    scrape_interval: 30s
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__metrics_path__]
      regex: (.*)
      target_label: metrics_path
    - source_labels: [__meta_kubernetes_node_label_kubernetes_io_os]
      action: keep
      regex: "windows"
    metric_relabel_configs:
    - source_labels: [__name__]
      action: keep
      regex: "up"
    kubernetes_sd_configs:
    - role: node
