  scrape_configs:
  - job_name: prometheus_collector_health
    scrape_interval: $$SCRAPE_INTERVAL$$
    label_limit: 63
    label_name_length_limit: 511
    label_value_length_limit: 1023
    static_configs:
    - targets: ['127.0.0.1:2234']
