scrape_configs:
  - job_name: windows-exporter
    scheme: http
    scrape_interval: $$SCRAPE_INTERVAL$$
    label_limit: 63
    label_name_length_limit: 511
    label_value_length_limit: 1023
    relabel_configs:
    - source_labels: [__address__]
      replacement: '$$NODE_NAME$$'
      target_label: instance
    static_configs:
    - targets: ['$$NODE_IP$$:19182']
